perspective-openstack/start.sh usr/share/perspective/perspective-openstack
perspective-openstack/target/lib usr/share/perspective/perspective-openstack
perspective-openstack/target/perspective-openstack.jar usr/share/perspective/perspective-openstack
etc/perspective/openstack/worker.properties etc/perspective/openstack
etc/perspective/worker/log4j.properties etc/perspective/openstack
etc/perspective/worker/clouds.xml etc/perspective/openstack
